### ISSUE TITLE
Getting EOF error which call APNS with developement certificate

### ISSUE THREAD

**Issue by anandhkumar** [sideshow/apns2#166]
**What version of Go are you using? go version**
go version go1.13 linux/amd64

**What OS and processor architecture are you using? go env**
OS: CentOS-7
x86_64 GNU/Linux

**What did you do?**
1. Span 100 threads using goroutine reach thread read data from redis,data is in json which contains  key csv_file path.Each csv contains 1000 tokens.
2. Each thread pop data from redis and read csv and spawn 1000 threads, how much tokens that much thread and call APNS push.
3. During the push getting "EOF". 90% calls failed with this error.
4. I have set my OS ulimit is 500000

**what did you expect to see?**
  It should get processed 10M tokens in 1 minute

**What did you see instead?**
I am getting following error when call APNS sevice with load testing on dev certificate
time="2020-02-25T08:54:44-05:00" level=info msg="Push Error:%!(EXTRA *url.Error=Post https://api.sandbox.push.apple.com/3/device/eoQtFQtlL4s:APA91bGrV0HqQH4qbxe
ZCJrX-XMHj63: EOF)"
90% calls failed with this error.
each thread with 1000 tokens publishe taken 2s with EOF error which is extermelly slow.
    
**_Further informations:_**
**Aim:**
My aim is publish 10M tokens in 1 minute 

**Where I run the code:**
I am running in golang code in aws EC2 instance in Virginia us-east-1

**My question:**
1. When this error came and how can I fix?

It will be  great if I can get help.

**Comment by sideshow** [comment]
Hi @anandhkumar my guess is that its because you're trying to load test on apples dev servers and they are just killing your connection -- Its very unlikely you will get anything like 10M tokens in 1 minute on their dev servers as they are meant for testing in small batches. You should be able to verify where the EOF is coming from by using `GODEBUG=http2debug=2`

**Comment by anandhkumar** [comment]
Thanks for you reply.
 Event I have tried with production certificate with production token. I got throughput of 4 lakes token processed in 1 minutes. 
Can I get any design in golang which I can able to process 10M in 1 minutes?
Following are the work flow of my golang
1. Pop json from redis
2. Json have csv file. Each pop csv file contains 1000 tokens. So we have 10000 json in redis.
3. Download csv file from S3 bucket
4. Csv file containes token. 
5. Call APNS with this token in one by one call. Bcs we have different token, differnt payload and message
Please guid me to do that.

**Comment by anandhkumar** [comment]
Can you please help me here to resolve this issue?

**Comment by anandhkumar** [comment]
Can sombody help me here?
When I do the load testing I am still getting 
Push Error:%!(EXTRA *url.Error=Post https://api.push.apple.com/3/device/eoQtFQtlL4s:APA91bGrV0HqQH4qbxeZCJrX-XMHj998: read tcp 172.30.0.244:41060->17.188.151.27:443: read: connection reset by peer)

Any body facing this issue?

**Comment by anandhkumar** [comment]
Team,
  Please help me to resolve this issue

**Comment by hopwesley** [comment]
I have the same problem

**Comment by bmueller** [comment]
I just started getting a bunch of EOF errors as well.

**Comment by sideshow** [comment]
This error happens when you're sending too many notifications to one device. 

Apple has a limit on the number of push notifications you can send to a single device within a timespan. If you exhaust this limit you will get a Response with a `429` StatusCode and a `TooManyRequests` Reason description. If you continue to push when you receive that error then the Apple push gateway may treat it as a denial-of-service attack, and temporarily block your server from sending notifications. The connection is cut by apple giving an `EOF` error. Usually you just have to wait for an hour or so and the error will resolve itself, and your notifications will start working again.

I'm closing this issue off, and have added a note to the [wiki](https://github.com/sideshow/apns2/wiki/Push-Troubleshooting#im-getting-a-eof-error-when-i-push) to explain. If you are still getting EOF errors and you aren't spamming a since device, then feel free to open another issue.
