### ISSUE TITLE
how to check health of the connection?

### ISSUE THREAD

**Issue by deamonwatcher** [sideshow/apns2#19]
when i create a new client，how can i check health of it ?
In Apple Privider Api Doc, it said: "You can check the health of your connection using an HTTP/2 PING frame." In your "Push" fuction, you said:
 "If the underlying http.Client is not currently connected, this method will attempt to reconnect transparently before sending the notification."
so, did i need do something else to keep alive of the connetion?

**Comment by sideshow** [comment]
Because we use the higher level HTTP Client which is designed to abstract the complexity of the underlying HTTP/2 connection and make it look like standard HTTP, currently there is no way to check the health of a connection.

That said, If you init a `apns2.Client` and hold on to it it will stay open until something happens (network connection drops etc). In the advent that it does drop, it would just transparently re-connect the next time you call Push() and stay open again.

Theoretically you could do this if you dropped down to using `x/net/http2` ping frames etc, but we haven't yet needed to do so. Just keeping a handle on the `apns2.Client` should be sufficient.

**Comment by c3mb0** [comment]
See https://github.com/sideshow/apns2/pull/45 for a potential solution.

**Comment by sideshow** [comment]
Closing as stale but have noted as a feature in #88
