### ISSUE TITLE
it response stautscode=200, means push successful. but my iphone can't received

### ISSUE THREAD

**Issue by jiangyilong** [sideshow/apns2#38]
hi.
  when I use it  push message to apple's push server, it response stautscode=200, means push successed. but sometings my iphone can't received the push message. 
  why not 100% received push message by iphone. it's normal or is bug.

it,s my logs.
[2016/09/01 20:47:03 CST] [INFO] (main.pushApnsAndSaveException:125) OK APNs ID:%!(EXTRA string=A9D9C902-0565-75D2-8A43-8F8BB92C1297, string=,StatusCode:, int=200, string=,Reason:, string=, string=,Timestamp:, apns2.Time=0001-01-01 00:00:00 +0000 UTC)

**Comment by sideshow** [comment]
Hey @jiangyilong,
This wont be an APNS/2 issue. If you are getting a 200 back that means it has been sent to Apple successfully, so the problem you are will be outside APNS/2.

Could it be that you arent receiving notifictions when the App is open? If so make sure you implement `- application:didReceiveRemoteNotification:` inside the app delegate otherwise you will only see notifications when the app is closed.

**Comment by jiangyilong** [comment]
hi@sideshow
thank you.
I had implement the application:didReceiveRemoteNotification: inside the app.
APNS/2 return stautscode=200 only send message to Apple server,  is not  Apple send push message to iphone(my app).  So it's maybe Apple issue.  it can't 100% push the message to App.

**Comment by nordicdyno** [comment]
@jiangyilong do you use non-zero Badge field in APNS messages?

**Comment by nathany** [comment]
Can you share the notification being sent to Apple to help debug the issue? 

Also, you can run your Go program with `GODEBUG=http2debug=1` on the command line to see the requests and response to Apple.

**Comment by jiangyilong** [comment]
@nordicdyno below is mine code：
	payload := NewPayload()
	payload.Alert(pMsg.Content)
	payload.Badge(pMsg.Count)
	payload.Custom("id", pMsg.Id)
	payload.Custom("type", pMsg.Type)
	payload.Custom("contentType", pMsg.ContentType)
	payload.Sound("sms-received1.caf")

I send the Badge field, it's non-zero Badge. but I tested if not set the Badge field, the APNS2 default 1.

**Comment by jiangyilong** [comment]
@nathany  thank you. I will try it.

**Comment by nordicdyno** [comment]
@jiangyilong Recently I have had problems with message delivery to APNS with Badges (we always set it to 1) Probably because our app doesn't handle them and iOS use some deduplication logic (just a guess). Or maybe it was an application issue. Anyway, I'm not iOS developer so I just removed Badge from all messages and things go better.
