### ISSUE TITLE
Error:net/http: Client Transport of type *http2.Transport doesn't support CancelRequest; Timeout not supported

### ISSUE THREAD

**Issue by sugarwyc** [sideshow/apns2#64]
run demo, throw error:
```
Error:net/http: Client Transport of type *http2.Transport doesn't support CancelRequest; Timeout not supported
```

1. go version go1.5.4 darwin/amd64
2. macOS 10.12.1

**Comment by sideshow** [comment]
Thanks for picking this up. Looks like `CancelRequest` is now removed in the new versions of `golang.org/x/net/http2` which is causing this error. 

In terms of fixing your error, the best bet is to use go 1.6 (1.6.4) or if you absolutely cant use 1.6 then you would need to find the version of golang.org/x/net/http2 before the CancelRequest was removed and use that.

(Because go1.5.4 is now over 2 versions old I will remove support for this on APNS/2)

**Comment by silver0511** [comment]
Hi，when i execute this code(res, err := client.Push(notification)), it cost about 1~3 seconds. but i want push more(probably push 1000 per second). how can i improve the performance. Thanks

**Comment by sideshow** [comment]
@silver0511 please start a new issue as you question is unrelated to this one.

**Comment by silver0511** [comment]
thanks. i will
