### ISSUE TITLE
About apns2 notification's  feedback  ?

### ISSUE THREAD

**Issue by xluohome** [sideshow/apns2#77]
hi,  when ios app is  reinstalled and  device token is changed .  but   `client.Push()`  push old‘s device token   returned  200 status code ?  thanks.

**Comment by sideshow** [comment]
Yes, It will take some time for an uninstalled device to be marked inactive on Apples servers and for them them to return a `410` status code. 

Last time I checked this was up to a day later on development gateway - I suspect its faster on the production gateway.

**Comment by xluohome** [comment]
@sideshow Thanks again .
I tried  testting for this  isssue.     24 hours later  on the old‘s device token ，The `client.Push()`   always  return a  200 status code . That is production mode .

**Comment by sideshow** [comment]
Hey @xluohome,
What does it say now? Did you test again as I'm curious what the actual period is before Apple marks it as dead.

**Comment by chrisrecalis** [comment]
From my experience they never get marked for cleanup. As long as the client re-installs the app before you are able to send a push they will always come back as 200. You can do this as many times as you want. I've seen some devices have 10+ tokens that point to the same device all return 200 back from apns. However only one of those tokens actually sends the notification to the device.

**Comment by sideshow** [comment]
Just wanting to close this issue off as it's not a bug. We're running this in production at scale daily with millions of devices and it works well. I've also tested on development gateway and it works well. 

Some more info; 

- There can be a delay between when you uninstall an app and when Apple will give you back the `410` Uninstalled status code. Apple doesn't document what the actual delay is, but I tested this yesterday and it was ~1h hour on the Development gateway. 

- Until you get a `410` back Apple will continue to give you a `200` which will look like the push went though (it didn't).

- The timestamp you get back from Apple with the `410` is not the exact uninstall date, it's the last date/time that Apple determined that it could not reach the device (for our purposes it's close enough).

- Lastly, If you're testing this and can't get a `410` back even after waiting for hours and hours, this is most likely because you need at least one other push enabled app installed on your device to maintain the connection with APNS. See Apple technical note [here](https://developer.apple.com/library/content/technotes/tn2265/_index.html#//apple_ref/doc/uid/DTS40010376-CH1-TNTAG34) and Stack overflow issue [here](http://stackoverflow.com/questions/39290613/apns-http2-api-not-returning-status-410-after-uninstalling-app)

**Comment by codybunea** [comment]
Hey @sideshow @chrisrecalis --

We were experiencing the same thing in production, where multiple re-installs will generate new tokens for the device, that never get marked for cleanup.  All tokens return `200` codes on push, even though only one push is received against the most recent token.

From our testing, when a user does eventually uninstall the app from the phone, **all** of the tokens (including the orphans) are returned as uninstalled from APNS.  We were seeing about a ~10 min delay between uninstalling, and APNS returning us a `410`, rather than a `200` against the production gateway (although this varies a bit as @sideshow mentioned).

**Comment by sideshow** [comment]
Thanks @codybunea / @chrisrecalis

Great find - I will add this info to a Wiki Page.
